### ISSUE TITLE
YouTube problem

### ISSUE THREAD

**Issue by tiktuk** [umetzu/DisableGoogleRedirect#1]
With this extension enabled I can't play videos on YouTube.com. Nothing happens when I click.

Safari Version 11.0 (12604.1.38.1.7)

In the console:

	[Error] InvalidAccessError
	open (Script Element 1:1:839)
	rF (base.js:2239:151)
	sF (base.js:2228)
	uF (base.js:2237)
	hH (base.js:2346:218)
	ZG (base.js:2333:116)

**Comment by umetzu** [comment]
Did you change the Info.plist? It should only run on the domains listed there. 
Maybe is a different extension you have installed?

**Comment by tiktuk** [comment]
Hmm, no but now it works sometimes actually. I think it's probably not your extension anyway. Maybe something else reloaded while I disabled/enabled extensions.

Thanks for the extension btw ☺️ .
